"""Equivalence test: the refactored usage readers must match the originals.

The originals are re-implemented here verbatim from the pre-refactor source
(git baseline 2adaaf5) and run against the same synthetic log as the new
index-backed code. Any divergence in the numbers is a regression.

The synthetic rows come from a small deterministic generator rather than the
``random`` module: a regression test must produce the same data on every run,
so a failure can always be reproduced.

All file access goes through ``log_open()``, which resolves the path and
proves it stays inside the temp directory this test created. The path is
generated by ``tempfile`` in the first place, but keeping the containment
check explicit means the test can only ever touch its own fixture.
"""
import json
import os
import shutil
import sys
import tempfile
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

MODELS = ["deepseek-v4.1-flash", "gpt-6-astra", "hy4-preview", "glm-5.3", "kimi-k3"]
REALMS = ["intl", "cn"]

failures = []


def check(name, expected, actual):
    if expected == actual:
        print("  PASS  %s" % name)
    else:
        print("  FAIL  %s" % name)
        print("        expected: %r" % (expected,))
        print("        actual  : %r" % (actual,))
        failures.append(name)


class Seq(object):
    """Deterministic pseudo-sequence for building fixtures."""

    def __init__(self, seed=12345):
        self.state = seed

    def next(self):
        # xorshift: stable across runs and platforms
        x = self.state
        x ^= (x << 13) & 0xFFFFFFFF
        x ^= (x >> 17)
        x ^= (x << 5) & 0xFFFFFFFF
        self.state = x & 0xFFFFFFFF
        return self.state

    def pick(self, items):
        return items[self.next() % len(items)]

    def below(self, n):
        return self.next() % n

    def chance(self, percent):
        return (self.next() % 100) < percent


# ---------------------------------------------------------------------------
# Fixture root. Every path used below is derived from it and re-validated on
# each open, so this test cannot reach outside the directory it created.
# ---------------------------------------------------------------------------
FIXTURE_ROOT = os.path.realpath(tempfile.mkdtemp(prefix="wbequiv_"))
LOG_PATH = os.path.join(FIXTURE_ROOT, "usage.jsonl")


def log_open(mode="r", **kwargs):
    """Open the fixture log, refusing any path outside FIXTURE_ROOT."""
    resolved = os.path.realpath(LOG_PATH)
    if resolved != os.path.join(FIXTURE_ROOT, "usage.jsonl"):
        raise ValueError("fixture log path escaped the fixture root")
    if os.path.commonpath([resolved, FIXTURE_ROOT]) != FIXTURE_ROOT:
        raise ValueError("refusing to open a path outside the fixture root")
    return open(resolved, mode, **kwargs)


rng = Seq()
rows = []
for i in range(500):
    realm = rng.pick(REALMS)
    row = {
        "at": time.time() - rng.below(5 * 86400),
        "iso": "2026-09-17T10:00:00",
        "model": rng.pick(MODELS),
        "realm": realm,
        "stream": bool(rng.below(2)),
        "elapsed_ms": 200 + rng.below(8800),
        "ttft_ms": 80 + rng.below(1120),
        "gen_ms": 100 + rng.below(7900),
        "prompt_tokens": 10 + rng.below(9000),
        "completion_tokens": 5 + rng.below(4000),
        "reasoning_tokens": rng.below(900),
        "cached_tokens": rng.below(5000),
        "total_tokens": 0,
        "credit": round(rng.below(10000) / 10000.0, 4),
        "tokens_per_sec": round(3 + rng.below(8700) / 100.0, 2),
        "cache_hit_pct": round(rng.below(9900) / 100.0, 1),
        "msgs_sha": "abc123",
        "n_msgs": 1 + rng.below(20),
    }
    row["total_tokens"] = row["prompt_tokens"] + row["completion_tokens"]
    if rng.chance(12):
        rows.append({
            "at": row["at"], "iso": row["iso"], "model": row["model"],
            "realm": realm, "error": True, "status": 503,
            "message": "upstream rejected", "elapsed_ms": row["elapsed_ms"],
        })
        continue
    if rng.chance(10):
        row.pop("account", None)          # unattributed
    else:
        row["account"] = "uid%02d" % (1 + rng.below(3))
    if rng.chance(8):
        row.pop("realm")                  # legacy row: resolver must infer
    if rng.chance(7):
        row.pop("ttft_ms")
    rows.append(row)

with log_open("w", encoding="utf-8") as fh:
    for row in rows:
        fh.write(json.dumps(row, ensure_ascii=False) + "\n")

print("synthetic log: %d rows, %d bytes"
      % (len(rows), os.path.getsize(LOG_PATH)))


# ---------------------------------------------------------------------------
# ORIGINAL implementations, copied from the pre-refactor source.
# ---------------------------------------------------------------------------
def orig_recent_usage(limit=100):
    out_rows, total = [], 0
    with log_open(encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                item = json.loads(line)
            except Exception:
                continue
            total += 1
            out_rows.append(item)
    return {"total": total, "rows": out_rows[-limit:]}


def orig_usage_by_account():
    buckets = {}
    with log_open(encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
            except Exception:
                continue
            if row.get("error"):
                continue
            key = row.get("account") or "(unattributed)"
            bucket = buckets.setdefault(key, {
                "account": key, "requests": 0, "prompt_tokens": 0,
                "completion_tokens": 0, "reasoning_tokens": 0,
                "cached_tokens": 0, "total_tokens": 0, "models": {},
            })
            bucket["requests"] += 1
            for field in ("prompt_tokens", "completion_tokens",
                          "reasoning_tokens", "cached_tokens", "total_tokens"):
                bucket[field] += row.get(field) or 0
            model = row.get("model") or "?"
            bucket["models"][model] = bucket["models"].get(model, 0) + 1
    out = sorted(buckets.values(), key=lambda b: -b["total_tokens"])
    for item in out:
        item["models"] = sorted(item["models"].items(), key=lambda kv: -kv[1])[:5]
    return out


def read_all_rows():
    out = []
    with log_open(encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                out.append(json.loads(line))
            except Exception:
                continue
    return out


# ---------------------------------------------------------------------------
print()
print("=" * 70)
print("A. recent_usage equivalence")
print("=" * 70)
import wb_usagelog

for limit in (100, 7, 1000):
    idx = wb_usagelog.UsageLog(LOG_PATH)
    idx.refresh(realm_of=wb_usagelog.realm_resolver())
    new_total, new_rows = idx.recent(limit=limit)
    orig = orig_recent_usage(limit=limit)
    check("recent(limit=%d).total" % limit, orig["total"], new_total)
    check("recent(limit=%d).rows" % limit, orig["rows"], new_rows)

print()
print("=" * 70)
print("B. usage_by_account equivalence")
print("=" * 70)
idx = wb_usagelog.UsageLog(LOG_PATH)
idx.refresh(realm_of=wb_usagelog.realm_resolver())
check("by_account()", orig_usage_by_account(), idx.by_account())

print()
print("=" * 70)
print("C. perf aggregation equivalence (window >= log size)")
print("=" * 70)
idx = wb_usagelog.UsageLog(LOG_PATH, window=len(rows) + 10)
idx.refresh(realm_of=wb_usagelog.realm_resolver())
tail = idx.tail(sample=0)


def sums(rows_in):
    ok_rows = [r for r in rows_in if not r.get("error")]
    ttfts = [r["ttft_ms"] for r in ok_rows if r.get("ttft_ms") is not None]
    gens = [r["gen_ms"] for r in ok_rows if r.get("gen_ms") is not None]
    walls = [r["elapsed_ms"] for r in ok_rows if r.get("elapsed_ms") is not None]
    rates = [r["tokens_per_sec"] for r in ok_rows if r.get("tokens_per_sec")]
    hits = [r["cache_hit_pct"] for r in ok_rows if r.get("cache_hit_pct") is not None]
    return {"total": len(rows_in), "ok": len(ok_rows),
            "ttft_n": len(ttfts), "ttft_sum": sum(ttfts),
            "gen_n": len(gens), "gen_sum": sum(gens),
            "wall_n": len(walls), "wall_sum": sum(walls),
            "rate_n": len(rates), "hit_n": len(hits)}


check("perf tallies", sums(read_all_rows()), sums(tail))

print()
print("=" * 70)
print("D. totals/by_model equivalence (realm filtered)")
print("=" * 70)
TOKEN_FIELDS = ("prompt_tokens", "completion_tokens", "reasoning_tokens",
                "cached_tokens", "total_tokens", "credit")


def orig_totals(realm, all_rows):
    """Reference implementation of the pre-refactor usage_snapshot() loop.

    Copied from baseline 2adaaf5: each model bucket carries `requests`, an
    `accounts` map of per-account request counts, and the token fields.
    """
    tot = {"requests": 0, "errors": 0}
    for f in TOKEN_FIELDS:
        tot[f] = 0
    by_model = {}
    for r in all_rows:
        row_realm = r.get("realm")
        if not row_realm:
            row_realm = "intl"       # resolver semantics for legacy rows
        if row_realm != realm:
            continue
        if r.get("error"):
            tot["errors"] += 1
            continue
        tot["requests"] += 1
        for f in TOKEN_FIELDS:
            if f in r:
                tot[f] += (r[f] or 0)
        m = r.get("model") or "unknown"
        per = by_model.setdefault(
            m, {"requests": 0, "accounts": {}, **{k: 0 for k in TOKEN_FIELDS}})
        per["requests"] += 1
        for f in TOKEN_FIELDS:
            if f in r:
                per[f] += (r[f] or 0)
        acct_id = r.get("account")
        if acct_id:
            per["accounts"][acct_id] = per["accounts"].get(acct_id, 0) + 1
    return tot, by_model


all_rows = read_all_rows()
idx = wb_usagelog.UsageLog(LOG_PATH, window=len(rows) + 10)
idx.refresh(realm_of=wb_usagelog.realm_resolver())
for realm in ("intl", "cn"):
    et, ebm = orig_totals(realm, all_rows)
    check("totals(%s)" % realm, et, idx.totals(realm))
    check("by_model(%s)" % realm, ebm, idx.by_model(realm))

print()
print("=" * 70)
print("E. incremental append == full rebuild")
print("=" * 70)
idx_inc = wb_usagelog.UsageLog(LOG_PATH)
idx_inc.refresh(realm_of=wb_usagelog.realm_resolver())
for i in range(60):
    row = {
        "at": time.time(), "iso": "now", "model": rng.pick(MODELS),
        "realm": "intl", "account": "uid01", "stream": True,
        "elapsed_ms": 500, "ttft_ms": 100, "gen_ms": 400,
        "prompt_tokens": 100, "completion_tokens": 50,
        "reasoning_tokens": 0, "cached_tokens": 10, "total_tokens": 150,
        "credit": 0.01, "tokens_per_sec": 20.0, "cache_hit_pct": 10.0,
    }
    with log_open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(row, ensure_ascii=False) + "\n")
idx_inc.refresh(realm_of=wb_usagelog.realm_resolver())

idx_full = wb_usagelog.UsageLog(LOG_PATH)
idx_full.refresh(realm_of=wb_usagelog.realm_resolver())
check("incremental totals == rebuilt", idx_full.totals(), idx_inc.totals())
check("incremental by_model == rebuilt", idx_full.by_model(), idx_inc.by_model())
check("incremental by_account == rebuilt", idx_full.by_account(), idx_inc.by_account())

print()
print("=" * 70)
print("F. partial trailing line must not be consumed")
print("=" * 70)
idx_p = wb_usagelog.UsageLog(LOG_PATH)
idx_p.refresh(realm_of=wb_usagelog.realm_resolver())
before = idx_p.stats()["parsed"]
with log_open("a", encoding="utf-8") as fh:
    fh.write('{"at": 1, "model": "gpt-6-astra", "realm": "intl", "prompt_tokens"')
idx_p.refresh(realm_of=wb_usagelog.realm_resolver())
check("partial line not parsed", before, idx_p.stats()["parsed"])
with log_open("a", encoding="utf-8") as fh:
    fh.write(': 5, "completion_tokens": 5, "total_tokens": 10}\n')
idx_p.refresh(realm_of=wb_usagelog.realm_resolver())
check("completed line parsed exactly once", before + 1, idx_p.stats()["parsed"])

print()
print("=" * 70)
print("G. truncation/rotation triggers rebuild")
print("=" * 70)
with log_open("w", encoding="utf-8") as fh:
    fh.write(json.dumps({"at": 1, "model": "m", "realm": "intl",
                         "prompt_tokens": 1, "completion_tokens": 1,
                         "total_tokens": 2, "account": "x"}) + "\n")
idx_p.refresh(realm_of=wb_usagelog.realm_resolver())
check("totals after truncation",
      {"requests": 1, "errors": 0, "prompt_tokens": 1, "completion_tokens": 1,
       "reasoning_tokens": 0, "cached_tokens": 0, "total_tokens": 2, "credit": 0},
      idx_p.totals("intl"))

shutil.rmtree(FIXTURE_ROOT, ignore_errors=True)

print()
print("=" * 70)
if failures:
    print("RESULT: %d FAILURE(S)" % len(failures))
    for f in failures:
        print("  - %s" % f)
    sys.exit(1)
print("RESULT: ALL EQUIVALENCE CHECKS PASSED")
